_target_: demo_generation.demogen.DemoGen

data_root: data
source_name: bookshelf

task_n_object: 2

use_linear_interpolation: false
interpolate_step_size: 0.01

use_manual_parsing_frames: true
parsing_frames:
  motion-1: 
  skill-1: 
  motion-2: 
  skill-2: 

mask_names:
  object: "green book on the table"
  target: "brown wooden bookshelf"

trans_range:
  src:
    object: [[0, 0, 0], [0, 0, 0]]
    target: [[0, 0, 0], [0, 0, 0]]
  test:
    object: [[-0.10, -0.10, 0], [0.10, 0.10, 0]]
    target: [[-0.10, -0.10, 0], [0.10, 0.10, 0]]

generation:
  range_name: test
  n_gen_per_source: 16
  render_video: True
  mode: grid